### PR TITLE
Create SaveJson.htm

### PR DESCRIPTION
**Pull request by HJCDstudios**

### CODE REVIEW

**Comment by alex-Symbroson** [comment]
please check out
https://github.com/SymDSTools/Docs/blob/master/README.md
as well as
https://github.com/SymDSTools/Docs/blob/master/files/README.md
for a brief documentation for how to edit the docs

the generator uses the json files located in files/<LANG>/<SCOPE> to
generate the docs from it
so files/en/app/obj.json is for app functions

However I appreciate that you would like to contribute - would be grateful
if you keep it up :)

best regards

**Comment by HJCDstudios** [comment]
Sorry looks like i don't understand what you said, ill just leave the
documentation

**Comment by alex-Symbroson** [comment]
no worries you can still contact me if theres aanything you want to add to
the docs or if you spot anything off

**Comment by HJCDstudios** [comment]
Oh ok

**Pull request closed without merging**
